objects = main.o factorial.o readline.o

all: $(objects)
	gcc $(objects) -o myfactorial

main.o: main.c factorial.o readline.o
	gcc -c main.c

factorial.o: factorial.c
	gcc factorial.c -c

readline.o:	readline.c
	gcc -c readline.c

.PHONY: clean
clean: 
	rm -f $(objects) myfactorial